- name: Install ansible-runner package
  ansible.builtin.pip:
    name: ansible-runner

- name: Copy scripts to /usr/local/bin
  ansible.builtin.copy:
    dest: /usr/local/bin
    group: root
    mode: "0755"
    owner: root
    src: "{{ item }}"
  with_fileglob:
    - "usr/local/bin/*"

- name: Copy .profile
  ansible.builtin.copy:
    dest: /home/{{ ansible_runner_user }}
    group: "{{ ansible_runner_user }}"
    mode: "0744"
    owner: "{{ ansible_runner_user }}"
    src: "[home]/.profile"
