- name: Install ansible-runner package
  ansible.builtin.pip:
    name: ansible-runner

- name: Install yq
  vars:
    checksum: "md5:{{ ansible_runner_yq_checksum }}"
    directory: /usr/local/bin
    filename: "yq"
    group: root
    mode: "0755"
    owner: root
    url: "{{ __ansible_runner_yq_url }}"
  ansible.builtin.include_role:
    name: local.pegasuspad.fetch
    tasks_from: download.yml

- name: Install webhook application
  ansible.builtin.include_role:
    name: webhook
  vars:
    webhook_hook_configs: "{{ ansible_runner_hook_configs }}"
    webhook_user: "{{ ansible_runner_user }}"

- name: Copy scripts to /usr/local/bin
  ansible.builtin.copy:
    dest: /usr/local/bin
    group: root
    mode: "0755"
    owner: root
    src: "{{ item }}"
  with_fileglob:
    - "usr/local/bin/*"

- name: Install webhook handlers
  block:
  - name: Create /etc/webhook/hooks directory
    ansible.builtin.file:
      group: root
      mode: "0755"
      owner: root
      path: /etc/webhook/hooks
      state: directory
  - name: Copy hook handlers to /etc/webhook/hooks
    ansible.builtin.copy:
      dest: /etc/webhook/hooks
      group: root
      mode: "0755"
      owner: root
      src: "{{ item }}"
    with_fileglob:
      - "etc/webhook/hooks/*"

- name: Copy .profile
  ansible.builtin.copy:
    dest: /home/{{ ansible_runner_user }}
    group: "{{ ansible_runner_user }}"
    mode: "0744"
    owner: "{{ ansible_runner_user }}"
    src: "[home]/.profile"
