- name: Install ansible-runner package
  ansible.builtin.pip:
    name: ansible-runner

- name: Copy run-playbook.sh script
  ansible.builtin.copy:
    src: usr/local/bin/run-playbook.sh
    dest: /usr/local/bin
    owner: root
    group: root
    mode: "0755"
- name: Copy unlock.sh script
  ansible.builtin.copy:
    src: usr/local/bin/unlock.sh
    dest: /usr/local/bin
    owner: root
    group: root
    mode: "0755"
- name: Copy .profile
  ansible.builtin.copy:
    dest: /home/{{ ansible_runner_user }}
    group: "{{ ansible_runner_user }}"
    mode: "0744"
    owner: "{{ ansible_runner_user }}"
    src: "[home]/.profile"
