- name: Configure Ansible control nodes
  hosts: ansible_control_nodes
  become: true
  roles:
    - role: ansible-runner
    - role: webhook
      vars:
        webhook_user: "{{ ansible_runner_user }}"
