- name: Configure Ansible control nodes
  hosts: ansible_control_nodes
  become: true
  roles:
    - role: ansible-runner
    - role: webhook
      vars:
        webhook_user: ops

- name: Configure reverse proxy servers
  hosts: reverse_proxy_servers
  become: true
  gather_facts: true
  roles:
    - nginxinc.nginx

# - name: lab-nginx
#   hosts: test
#   become: true
#   tasks:
#     - name: Install NGINX
#       ansible.builtin.include_role:
#         name: nginxinc.nginx