#!/usr/bin/env bash

# Load environment variables. These are initially populated by cloud-init
source /etc/ansible-runner/environment.sh
: "${VAULT_PATH:?Variable VAULT_PATH not set or empty}"

# set default comment if one wasn't provided
: "${COMMENT:=Update secret ${KEY} via webhook}"

# Connect to the SSH agent. This SSH agent must have been previously started via `/usr/local/bin/unlock.sh`
# The environment file should export 'SSH_AUTH_SOCK' and 'SSH_AGENT_PID'.
if [ ! -f "$HOME/.ssh/environment" ]; then
  echo "The ssh keys are not unlocked! Run /usr/local/bin/unlock.sh from a terminal."
  echo "Aborting."
  exit 1
else
  . "$HOME/.ssh/environment" > /dev/null
  ps -ef | grep ${SSH_AGENT_PID} | grep ssh-agent$ > /dev/null || {
    rm "$HOME/.ssh/environment"
    echo "The ssh-agent is no longer running. Run /usr/local/bin/unlock.sh from a terminal."
    echo "Aborting."
    exit 1
  }
fi

source $HOME/.ssh/environment

cd "${VAULT_PATH}"

# pull latest version of vault before making changes
git pull --rebase

echo -n "${VALUE}" | /usr/local/bin/update-vault \
  "${VAULT_PATH}/vault.yml" \
  lab@/var/lib/ansible/vault-password \
  ${KEY} >/dev/null

git add vault.yml
git commit -m "${COMMENT}"
git push || git reset --hard origin/main
