#!/usr/bin/env bash

# Load environment variables. These are initially populated by cloud-init
source /etc/ansible-runner/environment.sh
: "${VAULT_PATH:?Variable VAULT_PATH not set or empty}"

# set default comment if one wasn't provided
: "${COMMENT:=Update secret ${KEY} via webhook}"

echo -n "${VALUE}" | /usr/local/bin/update-vault \
  "${VAULT_PATH}/vault.yml" \
  lab@/var/lib/ansible/vault-password \
  "${KEY}" >/dev/null

cd "${VAULT_PATH}"
git add vault.yml
git commit -m "${COMMENT}"
git push || git reset --hard origin/main
