config_manager_webhook_configs:
  - command-working-directory: /opt/config-manager
    execute-command: /opt/config-manager/bin/update-secrets.ts
    http-methods:
      - PUT
    id: update-secrets
    include-command-output-in-response: true
    include-command-output-in-response-on-error: true
    pass-environment-to-command:
      - envname: PAYLOAD 
        source: entire-payload
    response-headers:
      - name: Content-Type
        value: application/json
    trigger-rule:
      match:
        type: value
        value: "{{ config_manager_webhook_token }}"
        parameter:
          source: header
          name: X-Token
  - command-working-directory: /opt/config-manager
    execute-command: /opt/config-manager/bin/update-certificates.ts
    http-methods:
      - PUT
    id: update-certificates
    include-command-output-in-response: true
    include-command-output-in-response-on-error: true
    pass-environment-to-command:
      - envname: PAYLOAD 
        source: entire-payload
    response-headers:
      - name: Content-Type
        value: application/json
    trigger-rule:
      match:
        type: value
        value: "{{ config_manager_webhook_token }}"
        parameter:
          source: header
          name: X-Token

# __config_manager_scripts_config_path: directory to install config files for node.js scripts
__config_manager_scripts_config_path: /etc/opt/config-manager

# __config_manager_scripts_data_path: directory in which node.js data files will be saved
__config_manager_scripts_data_path: /var/opt/config-manager

# __config_manager_scripts_package_path: directory in which to install node.js package
__config_manager_scripts_package_path: /opt/config-manager