- name: Configure Ansible control nodes
  hosts: ansible_control_nodes
  become: true
  roles:
    - role: automation
      vars:
        automation_packages:
          - vault-manager
        automation_user: '{{ ansible_runner_user }}'
    - role: webhook
      vars:
        webhook_hook_configs: "{{ ansible_runner_hook_configs + vault_manager_webhook_configs }}"
        webhook_user: "{{ ansible_runner_user }}"
    - role: vault-manager
      vars:
        vault_manager_log_file: "{{ webhook_log }}"
        vault_manager_webhook_token: "{{ ansible_runner_webhook_token }}"
    - role: ansible-runner

- name: Configure certbot
  hosts: certbot
  become: true
  pre_tasks:
    - name: Remove apt-installed packages, if any
      ansible.builtin.apt:
        pkg: 
          - certbot
        state: absent
  roles:
    - role: automation
      vars:
        automation_packages:
          - certbot
        automation_user: ansible
    - role: certbot

- name: Configure reverse proxy servers
  hosts: reverse_proxy
  become: true
  gather_facts: true
  roles:
    - reverse-proxy
