- name: Configure Ansible control nodes
  hosts: ansible_control_nodes
  become: true
  roles:
    - role: ansible-runner

- name: Configure certbot
  hosts: certbot
  become: true
  pre_tasks:
    - name: Remove apt-installed packages, if any
      ansible.builtin.apt:
        pkg: 
          - certbot
        state: absent
  roles:
    - role: automation
      vars:
        automation_packages:
          - certbot
        automation_user: ansible
    - role: certbot

- name: Configure reverse proxy servers
  hosts: reverse_proxy
  become: true
  gather_facts: true
  roles:
    - reverse-proxy
