- name: Configure Ansible control nodes
  hosts: ansible_control_nodes
  become: true
  roles:
    - role: ansible-runner

- name: Configure certbot
  hosts: certbot
  become: true
  pre_tasks:
    - name: Remove apt-installed packages, if any
      ansible.builtin.apt:
        pkg: 
          - certbot
        state: absent
  roles:
    - role: certbot
      vars:
        certbot_certs:
          - domains: ['foo-e.lab.pegasuspad.com']
        certbot_testmode: true

- name: Configure reverse proxy servers
  hosts: reverse_proxy_servers
  become: true
  gather_facts: true
  roles:
    - nginxinc.nginx

# - name: lab-nginx
#   hosts: test
#   become: true
#   tasks:
#     - name: Install NGINX
#       ansible.builtin.include_role:
#         name: nginxinc.nginx