collections:
- name: community.general
  version: 9.2.0
- name: ansible.posix
  version: 1.5.4
- name: git+https://github.com/pegasuspad/ansible-roles.git,main

roles:
- name: geerlingguy.apache
  version: 4.0.0
- name: geerlingguy.certbot
  version: 5.1.0
- name: geerlingguy.nodejs
  version: 6.1.1
- name: nginxinc.nginx
  version: 0.24.3
- name: roles-ansible.restic
  version: v0.8.1
