- name: Configure Nextcloud servers
  hosts: nextcloud_servers
  become: true
  gather_facts: true
  roles:
    - role: local.pegasuspad.sudo
    - role: local.pegasuspad.users
    - role: local.pegasuspad.sshd
    - role: local.pegasuspad.apache
      vars:
        apache_modules:
          - name: dir
          - name: env
          - name: headers
          - name: mime
          - name: proxy
          - name: proxy_fcgi
          - name: rewrite
        apache_sites:
          - name: nextcloud
            template: nextcloud.conf.j2
    - role: local.pegasuspad.php
      vars:
        php_ini:
          apc.enable_cli: 1
          apc.shm_size: 64M
          memory_limit: 512M
          opcache.enable_cli: 1
          opcache.jit: 1255
          opcache.jit_buffer_size: 128M
          opcache.revalidate_freq: 60
    - role: local.pegasuspad.mariadb
      vars:
        mariadb_databases:
          - collation: "{{ __nextcloud_db_collation }}"
            encoding: "{{ __nextcloud_db_encoding }}"
            name: "{{ nextcloud_db.name }}"
        mariadb_root_password: "{{ nextcloud_db_root_password}}"
        mariadb_users:
          - name: "{{ nextcloud_db.username }}"
            password: "{{ nextcloud_db.password }}"
            privileges: "{{ nextcloud_db.name }}.*:ALL"
    - role: local.pegasuspad.nextcloud
      vars:
        nextcloud_use_fpm: false
