---
- name: (RESTORE) Restore backup - {{ nextcloud_snapshot_id }}
  hosts: nextcloud_servers
  become: yes
  pre_tasks:
    - name: (RESTORE) Ensure only one host is specified
      assert:
        that:
          - inventory_hostname == play_hosts[0]
        msg: "This playbook requires a single server to be specified. Please provide only one host using --limit option."
    - name: (RESTORE) Ensure a snapshot ID was specified
      assert:
        that:
          - nextcloud_snapshot_id is defined
          - nextcloud_snapshot_id | length > 0
        msg: "The 'nextcloud_snapshot_id' variable must be set and non-empty."
  tasks:
    - name: (RESTORE) Download snapshot - {{ nextcloud_snapshot_id }}
      include_role:
        name: local.pegasuspad.nextcloud
        tasks_from: actions/backup/download-snapshot.yml
    - name: (RESTORE) Restore database - {{ nextcloud_snapshot_id }}
      include_role:
        name: local.pegasuspad.nextcloud
        tasks_from: actions/backup/restore-db.yml
    - name: (RESTORE) Restore files - {{ nextcloud_snapshot_id }}
      include_role:
        name: local.pegasuspad.nextcloud
        tasks_from: actions/backup/restore-files.yml