- name: Configure Nextcloud servers
  hosts: nextcloud_servers
  become: true
  gather_facts: true
  roles:
    - role: local.pegasuspad.users
    - role: local.pegasuspad.sudo
    - role: local.pegasuspad.sshd