# ansible_runner_user: username as which Ansible should be run
ansible_runner_user: root

# ansible_runner_yq_checksum: MD5 checksum for the specified version of yq
ansible_runner_yq_checksum: 900cfcede41a4ee180d7095956405b1e  

# ansible_runner_yq_version: version of the yq utility to install
ansible_runner_yq_version: 4.40.5

# ansible_runner_hook_configs: define the webhooks to implement
ansible_runner_hook_configs:
  - command-working-directory: /etc/webhook
    execute-command: /usr/local/bin/run-playbook.sh
    id: provision
    include-command-output-in-response: true
    pass-environment-to-command:
      - envname: TARGET_HOSTS
        name: host
        source: url
    trigger-rule:
      match:
        parameter:
          name: host
          source: url
        type: regex
        regex: "^lab-[-a-zA-Z0-9_.]+$"
  - command-working-directory: /etc/webhook
    execute-command: /etc/webhook/hooks/put-secret
    http-methods:
      - POST
    id: put-secret
    include-command-output-in-response: true
    pass-environment-to-command:
      - envname: COMMENT
        name: comment
        source: payload
      - envname: KEY
        name: key
        source: payload
      - envname: VALUE
        name: value
        source: payload
    response-headers:
      - name: Content-Type
        value: application/json
    response-message: '{"status":"OK"}'
    trigger-rule:
      match:
        type: value
        value: "{{ ansible_runner_webhook_token }}"
        parameter:
          source: header
          name: X-Token
