# certbot role
certbot_certs:
  - domains: ['coder.lab.pegasuspad.com']
  - domains: ['default.lab.pegasuspad.com']
certbot_config_manager_token: "{{ __vault__.config_manager_webhook_token }}"
certbot_proxy_host: reverse_proxy
certbot_testmode: true
certbot_webhook_host: lab-ansible
