---
# backup options
backup_no_log: false
backup_repositories:
  - name: '{{ nextcloud_backup_repository_name }}'
    aws_access_key: '{{ __vault__.nextcloud.backup_default.b2_access_key_id }}'
    aws_secret_access_key: '{{ __vault__.nextcloud.backup_default.b2_access_key_secret }}'
    location: s3:s3.us-east-005.backblazeb2.com/backup-pegasuspad-lab/nextcloud
    password: '{{  __vault__.nextcloud.backup_default.repository_password }}'
    schedule: '*-*-* 2:00:00'
  - name: prod_ro
    aws_access_key: '{{ __vault__.nextcloud.backup_prod_ro.b2_access_key_id }}'
    aws_secret_access_key: '{{ __vault__.nextcloud.backup_prod_ro.b2_access_key_secret }}'
    location: s3:s3.us-east-005.backblazeb2.com/backup-nextcloud-pegasuspad
    password: '{{  __vault__.nextcloud.backup_prod_ro.repository_password }}'

# mariadb options
# mariadb_data_directory: /var/lib/db/mysql
mariadb_version: 1:10.6*

# nextcloud options
nextcloud_backup_enabled: true
nextcloud_backup_path: /var/lib/backup
nextcloud_db:
  host: localhost
  name: nextcloud
  password: '{{ __vault__.nextcloud.db_password }}'
  port: 5432
  type: mysql
  username: '{{ __vault__.nextcloud.db_username }}'
nextcloud_host_name: nextcloud.lab.pegasuspad.com
nextcloud_proxy_host: 10.111.1.212
nextcloud_db_root_password: '{{ __vault__.nextcloud.db_root_password }}'
nextcloud_version: 27.1.11

# php options
php_version: 8.2
